name: faust-selenium-windows
channels:
    - conda-forge
dependencies:
    - python>=3.6
    - geckodriver
    - multidict
    - pip
    - pytz
    - selenium
    - websockets
    - pip:
      - faust
