name: faust-selenium
channels:
    - conda-forge
dependencies:
    - python>=3.6
    - geckodriver
    - lz4
    - jinja2
    - pip
    - python-snappy
    - pytz
    - selenium
    - sqlalchemy
    - supervisor
    - websockets
    - pip:
        - "faust[dbrocks]==1.7.4"
